export const READING_FONT_FAMILIES = [
  'Arial',
  'Georgia',
  'GoogleSans',
  'Inter',
  'Lato',
  'Lora',
  'Merriweather',
  'Montserrat',
  'MontserratAlternates',
  'NotoSans',
  'NotoSerif',
  'OpenSans',
  'PTSans',
  'PTSerif',
  'Raleway',
  'Roboto',
  'SpaceMono',
  'TimesNewRoman',
  'Verdana',
  'WorkSans',
] as const

export const APP_FONT_SOURCES = {
  Arial: require('../assets/fonts/Arial.ttf'),
  Georgia: require('../assets/fonts/Georgia.ttf'),
  GoogleSans: require('../assets/fonts/GoogleSans.ttf'),
  Inter: require('../assets/fonts/Inter.ttf'),
  Lato: require('../assets/fonts/Lato.ttf'),
  Lora: require('../assets/fonts/Lora.ttf'),
  Merriweather: require('../assets/fonts/Merriweather.ttf'),
  Montserrat: require('../assets/fonts/Montserrat.ttf'),
  MontserratAlternates: require('../assets/fonts/MontserratAlternates.ttf'),
  NotoSans: require('../assets/fonts/NotoSans.ttf'),
  NotoSerif: require('../assets/fonts/NotoSerif.ttf'),
  OpenSans: require('../assets/fonts/OpenSans.ttf'),
  PTSans: require('../assets/fonts/PTSans.ttf'),
  PTSerif: require('../assets/fonts/PTSerif.ttf'),
  Raleway: require('../assets/fonts/Raleway.ttf'),
  Roboto: require('../assets/fonts/Roboto.ttf'),
  SpaceMono: require('../assets/fonts/SpaceMono.ttf'),
  TimesNewRoman: require('../assets/fonts/TimesNewRoman.ttf'),
  Verdana: require('../assets/fonts/Verdana.ttf'),
  WorkSans: require('../assets/fonts/WorkSans.ttf'),
  BeVietnamPro: require('../assets/fonts/BeVietnamPro.ttf'),
} as const
